//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BasicCRUDWeb1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class basicTestEntities : DbContext
    {
        public basicTestEntities()
            : base("name=basicTestEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<client> clients { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
    
        public virtual int ClientDeleteById(string userId)
        {
            var userIdParameter = userId != null ?
                new ObjectParameter("userId", userId) :
                new ObjectParameter("userId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ClientDeleteById", userIdParameter);
        }
    
        public virtual ObjectResult<ClientViewAll_Result> ClientViewAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ClientViewAll_Result>("ClientViewAll");
        }
    
        public virtual ObjectResult<ClientViewById_Result> ClientViewById(string userId)
        {
            var userIdParameter = userId != null ?
                new ObjectParameter("userId", userId) :
                new ObjectParameter("userId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ClientViewById_Result>("ClientViewById", userIdParameter);
        }
    
        public virtual int CreateClientOrEidt(string userId, string username, string password, string email, string tel, Nullable<byte> disable)
        {
            var userIdParameter = userId != null ?
                new ObjectParameter("userId", userId) :
                new ObjectParameter("userId", typeof(string));
    
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var telParameter = tel != null ?
                new ObjectParameter("tel", tel) :
                new ObjectParameter("tel", typeof(string));
    
            var disableParameter = disable.HasValue ?
                new ObjectParameter("disable", disable) :
                new ObjectParameter("disable", typeof(byte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CreateClientOrEidt", userIdParameter, usernameParameter, passwordParameter, emailParameter, telParameter, disableParameter);
        }
    
        public virtual int spAddEmployee(string userID, string userName, string password, string email, string tel, Nullable<byte> disable)
        {
            var userIDParameter = userID != null ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", "");
    
            var userNameParameter = userName != null ?
                new ObjectParameter("UserName", userName) :
                new ObjectParameter("UserName", "");
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", "");
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", "");
    
            var telParameter = tel != null ?
                new ObjectParameter("Tel", tel) :
                new ObjectParameter("Tel", "");
    
            var disableParameter = disable.HasValue ?
                new ObjectParameter("Disable", disable) :
                new ObjectParameter("Disable", 0);
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spAddEmployee", userIDParameter, userNameParameter, passwordParameter, emailParameter, telParameter, disableParameter);
        }
    
        public virtual int spDeleteEmployee(string userID)
        {
            var userIDParameter = userID != null ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spDeleteEmployee", userIDParameter);
        }
    
        public virtual ObjectResult<spGetAllEmployee_Result> spGetAllEmployee()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetAllEmployee_Result>("spGetAllEmployee");
        }
    
        public virtual ObjectResult<spGetOneEmployee_Result> spGetOneEmployee(string userID)
        {
            var userIDParameter = userID != null ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetOneEmployee_Result>("spGetOneEmployee", userIDParameter);
        }
    
        public virtual int spUpdateEmployee(string userID, string userName, string password, string email, string tel, Nullable<byte> disable)
        {
            var userIDParameter = userID != null ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(string));
    
            var userNameParameter = userName != null ?
                new ObjectParameter("UserName", userName) :
                new ObjectParameter("UserName", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var telParameter = tel != null ?
                new ObjectParameter("Tel", tel) :
                new ObjectParameter("Tel", typeof(string));
    
            var disableParameter = disable.HasValue ?
                new ObjectParameter("Disable", disable) :
                new ObjectParameter("Disable", typeof(byte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spUpdateEmployee", userIDParameter, userNameParameter, passwordParameter, emailParameter, telParameter, disableParameter);
        }
    }
}
